In [1]:
#importing the libirary for this Module Program
import matplotlib as plt
import pandas as pd

In [2]:
#read the data from CSV file and store the value dataset variable
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
#ordinal data convert into true or fakse
dataset=pd.get_dummies(dataset)

In [5]:
dataset

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes
0,19,27.900,0,16884.92400,True,False,False,True
1,18,33.770,1,1725.55230,False,True,True,False
2,28,33.000,3,4449.46200,False,True,True,False
3,33,22.705,0,21984.47061,False,True,True,False
4,32,28.880,0,3866.85520,False,True,True,False
...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,False,True,True,False
1334,18,31.920,0,2205.98080,True,False,True,False
1335,18,36.850,0,1629.83350,True,False,True,False
1336,21,25.800,0,2007.94500,True,False,True,False
1337,61,29.070,0,29141.36030,True,False,False,True

In [6]:
#input  field assign into indep and output field assign into from dep
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [7]:
#train test split here we will pass the indep and dep  parameter then split X_train,y_train input and test data 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3,random_state = 0)

In [8]:
#preprocessing tool in machine learning that standardizes numeric features
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
#supervised machine learning algorithm that builds an ensemble of multiple decision trees

from sklearn.ensemble import RandomForestRegressor

In [10]:

from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['squared_error', 'absolute_error'],
'max_features': ['sqrt', 'log2', None],
'n_estimators':[10,100]}

#defined parameter values for the RF Regressor model

In [11]:
#GridSearchCV pass the RandomForestRegressor duntion,refit find the best result verbose is full debugging mode in most software and programming tools
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit=True, verbose=3, n_jobs=-1)

In [12]:
grid.fit(X_train, y_train)  #Model is trained and build

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error'],
                         'max_features': ['sqrt', 'log2', None],
                         'n_estimators': [10, 100]},
             verbose=3)

In [16]:
re=grid.cv_results_
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.090127,0.020753,0.008925,0.004046,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.796608,0.722280,0.827198,0.803755,0.747475,0.779463,0.038615,7
1,0.552865,0.049040,0.030273,0.002712,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.805770,0.767832,0.836915,0.827283,0.763941,0.800348,0.029916,2
2,0.059290,0.006589,0.005581,0.001141,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.782174,0.775485,0.761431,0.788177,0.735161,0.768486,0.018891,12
3,0.711157,0.012623,0.037126,0.003867,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.799966,0.769292,0.835056,0.828865,0.764326,0.799501,0.029246,4
4,0.089203,0.003862,0.006700,0.001873,squared_error,None,10,"{'criterion': 'squared_error', 'max_features':...",0.786880,0.727905,0.835326,0.766787,0.757904,0.774960,0.035659,10
5,0.659717,0.009319,0.028734,0.002096,squared_error,None,100,"{'criterion': 'squared_error', 'max_features':...",0.802972,0.749085,0.837414,0.810558,0.762721,0.792550,0.032326,5
6,0.144528,0.003521,0.005475,0.001507,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.779702,0.749621,0.810449,0.796845,0.751648,0.777653,0.024125,9
7,1.329297,0.018792,0.023917,0.002607,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.802137,0.776844,0.834469,0.822816,0.762665,0.799786,0.026993,3
8,0.135168,0.008999,0.005167,0.000858,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.777797,0.753214,0.799307,0.819154,0.745754,0.779045,0.027555,8
9,1.265196,0.018730,0.021463,0.002232,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.805604,0.774264,0.837620,0.832400,0.764185,0.802815,0.029671,1
10,0.209110,0.007463,0.006051,0.001061,absolute_error,None,10,"{'criterion': 'absolute_error', 'max_features'...",0.754657,0.772344,0.800890,0.765166,0.756111,0.769834,0.016800,11
11,1.698540,0.029654,0.015102,0.002187,absolute_error,None,100,"{'criterion': 'absolute_error', 'max_features'...",0.782384,0.771241,0.820633,0.814965,0.760487,0.789942,0.023843,6

GridSearchCV(cv='warn', error_score='raise-deprecating',
estimator=RandomForestRegressor(criterion='mse', max_depth=None,
max_features=None,
max_leaf_nodes=None,
min_impurity_decrease=0.0,
min_impurity_split=None,
min_samples_leaf=1,
min_samples_split=2,
min_weight_fraction_leaf=0.0,
presort=False, random_state=None,
splitter='best'),
iid='warn', n_jobs=-1,
param_grid={'criterion': ['mse', 'mae'],
'max_features': ['auto', 'sqrt', 'log2'],
'n_estimators': [10, 100]},
pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
scoring=None, verbose=3)

In [18]:
grid_predictions = grid.predict(X_test)## After Model creation ,it is evaluated using prediction)

In [19]:
grid_predictions

array([10828.28527465,  9168.35284885, 43888.8197583 , 13756.63316835,
        9868.3492383 , 10888.8957905 ,  2438.53479   , 11188.762232  ,
        7765.4076631 ,  5895.891289  ,  6229.9862186 , 12982.4231995 ,
        7928.3509258 ,  5832.8364653 , 23703.5040593 , 11875.1585026 ,
       14504.50154175,  4112.2367633 ,  6618.9401023 , 33210.22630055,
       23954.04742215, 15049.77650655, 11501.6625821 , 28221.74254   ,
        2228.3964204 ,  7819.7200071 ,  5150.5981295 ,  8403.2390908 ,
        3829.8782245 , 13739.7335471 ,  8560.7320761 , 46594.239262  ,
       14655.4476761 , 13291.7249221 , 18603.4215465 ,  4306.3630057 ,
        9123.5918689 , 37386.5386409 , 39224.59453715,  2339.2689015 ,
        5712.6974398 ,  3635.4929048 , 22449.5624314 , 46657.69327605,
       36861.7752267 ,  4066.2523374 , 12231.1115911 ,  6907.1548042 ,
        7061.5945245 , 13253.73912825,  4855.4606215 ,  4887.0437875 ,
       26968.52077995, 44416.0442003 , 11845.8544589 , 11559.5574407 ,
        4481.4177412 , 10483.87231005,  9889.1893114 , 14439.10427635,
        1763.5744538 , 44499.16320575, 16113.2289839 , 19664.812706  ,
       11316.5531613 , 10211.0939758 , 30608.03227915, 37842.59409365,
        5276.2133506 ,  9011.4692975 , 15998.0567939 , 11552.00002075,
       18733.1446031 , 15966.3620088 , 14364.8199206 , 13737.6832887 ,
       10168.33615735, 17794.0488759 , 21234.8875538 , 44234.4885783 ,
       11478.841908  , 45264.60172335,  3228.0124314 , 10550.9415259 ,
       39170.75965025, 20632.9024113 ,  4589.175053  ,  2966.5635618 ,
       12796.02561655, 37358.9544939 ,  5998.8848103 , 13941.18402685,
        3185.376166  , 10619.1000925 ,  9440.706012  ,  4732.6053623 ,
       43428.6611671 , 41368.0135574 ,  5241.3210465 , 11291.1135317 ,
        4193.5132475 ,  6092.0441337 ,  8717.068674  , 36814.9166427 ,
       25762.69879755,  4391.677511  , 11113.96398875,  4450.4757676 ,
       11558.4954415 , 44828.089356  , 11934.30947945,  7545.3187916 ,
       10011.92764765, 34336.60306175, 45856.1353157 ,  7316.0245065 ,
        2845.0906503 , 10824.83611895, 15978.04779465, 10299.187548  ,
       41282.8701089 , 12080.902785  , 13890.4660261 ,  8179.8760805 ,
       10067.3025512 ,  5107.348024  , 23715.3860632 , 25668.60794925,
       46616.3007363 ,  2064.381766  , 10404.5443107 ,  3734.3189201 ,
        6394.44276495,  9456.05059385, 33395.308715  , 34656.52263235,
       25647.93964565, 12926.13302455, 25043.2124597 ,  4123.8396607 ,
        1980.4890825 , 11911.64540935, 10603.4122417 , 10955.14965725,
        7069.7740059 , 13992.8700145 , 20414.59426605, 11886.558761  ,
        1911.5368818 , 11839.07085125,  6194.4663254 , 37024.7498413 ,
       10811.333321  ,  4884.1740155 ,  4963.497735  ,  7697.7331542 ,
        3239.5671114 ,  5417.300552  , 11875.1585026 ,  9902.307365  ,
        7076.0773296 , 13350.3634228 , 13794.3457662 , 10254.16137505,
        4836.5563453 ,  7103.6248285 , 17670.4676857 ,  8239.1430999 ,
        5042.4321117 ,  2190.30799825,  8036.6443016 ,  6414.4569999 ,
       10584.7039114 ,  2078.477602  ,  7302.9753781 ,  8283.9087665 ,
        4687.011148  ,  7105.82210705, 31628.7915815 ,  1706.478752  ,
       16562.36989875,  6878.8538418 , 11256.0443885 ,  5971.6403945 ,
        7407.87867425, 28504.3268279 ,  2604.7808414 ,  3462.3202534 ,
       13944.201245  , 10635.2541034 , 42514.86260665,  7760.2042769 ,
        5796.6730967 , 27823.73717965,  3655.9906615 ,  2721.8975493 ,
        7166.0361423 ,  6390.673851  ,  9515.8592228 ,  4978.2646899 ,
       12027.56846435, 45504.9475922 , 16360.37787455, 19141.6984105 ,
       11511.4502416 , 42831.37826415,  4775.3346978 , 10196.19073675,
       10078.9735987 ,  4113.878458  ,  9100.4565304 , 13978.7306558 ,
        8475.4949934 ,  5126.236201  ,  6527.3328101 ,  4815.6997516 ,
        6574.869384  ,  6761.0176106 , 14175.75388105,  6829.306693  ,
        8944.1122538 ,  7849.09986425, 11287.4473542 ,  7721.6503509 ,
       12344.8803582 , 14358.1598051 , 16154.24435015, 12459.6655789 ,
        7354.20797685,  2699.180851  ,  2859.3115162 ,  8570.5124608 ,
       14073.8757048 , 10266.3703228 ,  7035.5768368 ,  7270.9331794 ,
       11387.05104775, 32979.15316735,  6006.9805766 , 11791.16616935,
        6462.5284503 , 36465.47039045,  9403.5970958 ,  9743.2376812 ,
       11175.8942263 , 11759.5567601 ,  3605.3145624 ,  8849.448259  ,
        4631.817699  ,  6532.5236587 , 21261.2631478 , 44772.26172555,
        6305.7141009 ,  4496.428051  ,  8774.5638375 ,  1782.0790824 ,
        8408.5777685 ,  3391.863728  ,  7253.1179107 ,  9316.788576  ,
        8345.3491485 , 26006.7111757 , 44369.2567655 , 16663.18891665,
        6561.7387665 , 11532.5324047 , 41270.81004175, 10350.1737589 ,
       39675.20455585,  1180.082176  , 37170.91798325,  6470.6163288 ,
       13615.42756985,  8510.8289181 , 38254.0780001 ,  5559.3923475 ,
       10199.54278755,  9635.2722983 ,  5758.3556899 , 16299.95869455,
       11874.391624  ,  9341.2135405 , 15091.5501255 , 12674.5275095 ,
        6288.0890274 ,  5713.9746187 ,  9650.0125489 , 22744.4331553 ,
        4929.9083013 ,  1674.976996  ,  2849.3878795 , 44452.5867943 ,
       10761.6638646 ,  4494.7308289 , 15404.03345725, 13807.36532745,
       32435.5673333 ,  7733.2240461 ,  6344.8353046 ,  8722.96084945,
        3394.3219264 ,  4733.8906865 , 19732.3822166 , 19326.6899326 ,
       13627.9057803 ,  2740.348952  ,  3604.8875478 ,  9647.0720094 ,
       10823.38006375, 18429.3261279 , 20544.57537   ,  6926.2752389 ,
       18211.3695756 ,  3089.0963365 ,  6260.5914465 ,  8869.9664901 ,
       16597.1273509 ,  3558.6006415 ,  9020.1566272 , 44942.92233645,
        4939.3873654 ,  5098.87666975,  2046.459326  , 14335.5820744 ,
        5098.7647972 , 12571.8108051 , 43481.0246271 , 19629.9713882 ,
       10174.6711352 , 41600.0889479 , 14689.75002015, 12297.3555339 ,
       10161.37761245,  6309.9057867 , 29206.5756657 ,  4821.6506475 ,
       15436.5697514 ,  2612.4893002 , 18300.4767515 ,  3834.2000667 ,
       27223.6821342 ,  8947.5845508 ,  4168.4480954 , 36127.2022756 ,
        7872.4963238 ,  5259.671934  , 32952.8778491 ,  4099.3730178 ,
        9933.0535777 ,  3889.5162812 , 11153.8911851 ,  4507.4547928 ,
        6969.8176911 ,  7696.4105892 , 44982.9470675 , 11759.5991239 ,
       34595.8917961 , 35866.9279336 ,  6062.5868485 ,  8396.0401574 ,
        1794.6364307 ,  4842.8505886 ,  5341.5335251 ,  9377.0894162 ,
       45493.62252655, 11179.49864775,  2420.9979992 , 13076.05949235,
        2246.2786947 , 14156.4798351 , 11313.2437693 ,  3893.6095817 ,
        4970.4139015 , 35985.9698481 ,  6750.2893105 ,  2118.109391  ,
       40110.4926217 , 12568.19439985, 43269.4631007 , 11306.32904525,
        6546.8991036 ,  2855.0425604 ,  2214.758661  , 13364.43941555,
        5757.2794879 ,  2054.9746045 , 12610.36014095,  7573.4547643 ,
        6855.3053828 ,  7651.3865099 ,  9176.9440501 , 40465.63316825,
        2242.3451421 , 10644.6661284 ,  6966.8358285 , 15413.8269069 ,
       11238.8221107 ,  8048.1623641 , 19152.1881887 , 12719.6401592 ,
       16890.93240075, 19160.9951606 ,  4374.009145  ,  6214.3930887 ,
       12995.71503365,  9459.9570907 ,  6775.4578375 ,  4512.39585   ,
       33738.0230283 , 12986.14385955,  7230.912861  , 13756.1958318 ,
       12777.5538745 , 12816.58927765, 44876.6597186 ,  5852.0191185 ,
        9503.9532894 ,  1769.3772945 , 16049.66701085,  2338.9051982 ,
        7060.2110275 ,  2088.38125   , 12213.618669  ,  7798.4094605 ,
       11008.32029275, 41917.86496105,  5276.1535845 , 31560.3955284 ,
       22152.1710779 , 11570.1538052 , 12475.5348542 , 36636.9128627 ,
       12132.0650989 ,  3470.394969  ,  9891.78482705, 22579.01298685,
       36518.4586919 , 20358.5884281 ,  9710.7014796 , 37798.57734565,
        5572.788189  , 18373.6437183 ,  2860.373142  , 34727.72851475,
        7836.2379849 , 20167.56281035])

In [20]:
## 2. Assign the output to a new variable (e.g., score) to avoid overriding the function name
from sklearn.metrics import r2_score
r_score=r2_score(y_test,grid_predictions)

In [21]:
score measures how well a regression model explains the variance of target data
r_score

0.8741242063025312

In [ ]:
#get the below value on input
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=tint(input("Smoker Yes 0 or 1:"))

In [ ]:
#predict value from above input
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))